use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;

use crate::base::RiverbaseResult;

use super::engines::{DomainCommandEngine, DomainQueryEngine, DomainServiceEngine};
use super::meta::DomainMeta;

/// A bundled domain: one namespace with a command engine, a query engine, and an optional
/// service engine, plus compile-time identity (namespace / title / description).
///
/// Concrete domains are generated by the [`domain!`](crate::domain) macro and implement this
/// trait. The web/portal layer consumes `&dyn Domain` / `D: Domain` rather than a concrete type.
#[async_trait]
pub trait Domain: Send + Sync {
    /// Namespace.
    fn namespace(&self) -> &str;

    /// Casbin / policy identity for this domain. Defaults to [`Self::namespace`].
    ///
    /// Override when the HTTP wire name differs from the policy-pack namespace
    /// (for example wire `identity-manager` → policy `rfx.idm`).
    fn policy_identity(&self) -> &str {
        self.namespace()
    }

    /// Title.
    fn title(&self) -> &str;

    /// Description.
    fn description(&self) -> Option<&str>;

    /// Command dyn.
    fn command_dyn(&self) -> Arc<dyn DomainCommandEngine>;

    /// Query dyn.
    fn query_dyn(&self) -> Arc<dyn DomainQueryEngine>;

    /// Optional command capability. Query-only domains override this with `None`.
    fn command_capability(&self) -> Option<Arc<dyn DomainCommandEngine>> {
        Some(self.command_dyn())
    }

    /// Optional query/report capability. Command-only domains override this with `None`.
    fn query_capability(&self) -> Option<Arc<dyn DomainQueryEngine>> {
        Some(self.query_dyn())
    }

    /// Service dyn.
    fn service_dyn(&self) -> Option<Arc<dyn DomainServiceEngine>> {
        None
    }

    /// Assemble a [`DomainMeta`] view from the compile-time identity.
    fn meta(&self) -> DomainMeta {
        let mut meta = DomainMeta::new(self.namespace(), self.title());
        if let Some(description) = self.description() {
            meta = meta.with_description(description);
        }
        meta
    }

    /// Discovery document: namespace, identity, and registered command / query / service keys.
    async fn discovery(&self) -> RiverbaseResult<Value> {
        serde_json::to_value(super::manifest::build_domain_manifest(self).await?)
            .map_err(|err| crate::errors::DOM_014.with_data(err.to_string()))
    }
}
