//! Shared spawn runtime for domains.
//!
//! [`DomainRuntime`] is the single bundle every [`Domain`](crate::domain::Domain) constructor
//! receives: the database connection, the state manager, the audit log store, the message bus,
//! and the cross-domain [`CommandInvoker`]. It is the base parameter of the `spawn(...)` block
//! generated by [`domain!`](crate::domain).

use std::sync::Arc;

use tokio::task::AbortHandle;
use tracing::info;

use uuid::Uuid;

use crate::base::{RiverbaseResult, TenantPolicyResolver};
use crate::command::{
    spawn_process_manager_worker, MessageBus, ProcessManagerRegistry, ProcessManagerStore,
};
use crate::config::{RiverbaseConfig, MediaStorageConfig};
use crate::datastore::{PgPool, PostgresProcessManagerStore};
use crate::domain::{CommandInvoker, QueryInvoker};
use crate::logstore::{AuditLogConfig, DomainLogStore, PostgresDomainLogStore};
use crate::transport::connect::connect_stream_bus;
use crate::transport::StreamBus;

/// Tenant stamped onto engine contexts in [`DomainRuntime::postgres_test`].
pub const TEST_TENANT: Uuid = Uuid::from_u128(0x0000_0000_0000_4000_8000_0000_0000_0001);

/// Async Postgres pool plus DSN (for sync Diesel migrations).
#[derive(Clone)]
pub struct PgConnection {
    /// Pgpool.
    pub pgpool: Arc<PgPool>,
    /// Db dsn.
    pub db_dsn: String,
}

/// Persistence backend and connection handle for domain spawn.
#[derive(Clone)]
pub enum DbConnection {
    /// Postgres.
    Postgres(Arc<PgConnection>),
}

impl DbConnection {
    /// Postgres.
    pub fn postgres(&self) -> Option<&PgPool> {
        match self {
            Self::Postgres(conn) => Some(conn.pgpool.as_ref()),
        }
    }

    /// Db dsn.
    pub fn db_dsn(&self) -> Option<&str> {
        match self {
            Self::Postgres(conn) => Some(conn.db_dsn.as_str()),
        }
    }

    /// Whether this is postgres.
    pub fn is_postgres(&self) -> bool {
        matches!(self, Self::Postgres(_))
    }
}

/// Shared runtime dependencies for spawning domains in a service.
#[derive(Clone)]
pub struct DomainRuntime {
    /// Dbconn.
    pub dbconn: DbConnection,
    /// Logstore.
    pub logstore: DomainLogStore,
    /// Msgbus.
    pub msgbus: Arc<dyn MessageBus>,
    /// Realtime fanout bus (NATS/Redis; injected in tests).
    pub stream_bus: Arc<dyn StreamBus>,
    /// Retained worker abort handles for graceful shutdown ([RUN-03], [RUN-07]).
    workers: Arc<RuntimeWorkers>,
    /// Invoker.
    pub invoker: Arc<CommandInvoker>,
    /// Query invoker.
    pub query_invoker: Arc<QueryInvoker>,
    /// Process manager.
    pub process_manager: Arc<dyn ProcessManagerStore>,
    /// Process registry.
    pub process_registry: Arc<ProcessManagerRegistry>,
    /// Per-channel audit log switches (mirrors `[riverbase.audit_log]` config).
    pub audit_log: AuditLogConfig,
    /// Default `_tenant` for spawned engine contexts, resolved from config `tenant`.
    ///
    /// Production HTTP overwrites this from `AuthorizationContext.tenant`.
    /// In-process callers must set it with [`Self::with_tenant_id`] (or use
    /// [`Self::postgres_test`], which stamps [`TEST_TENANT`]).
    pub tenant_id: Option<Uuid>,
    /// Reject command payload properties not declared by the typed payload schema.
    pub deny_unknown_fields: bool,
    /// Filesystem root for `rfx.media` uploads (`[riverbase.media] fs_root` / `MEDIA_FS_ROOT`).
    pub media: MediaStorageConfig,
    /// Portal tenant access and stamp policy resolver.
    pub tenant_policies: TenantPolicyResolver,
}

#[derive(Default)]
struct RuntimeWorkers {
    handles: std::sync::Mutex<Vec<AbortHandle>>,
}

impl RuntimeWorkers {
    fn push(&self, handle: AbortHandle) {
        if let Ok(mut guard) = self.handles.lock() {
            guard.push(handle);
        }
    }

    pub fn abort_all(&self) {
        if let Ok(mut guard) = self.handles.lock() {
            for handle in guard.drain(..) {
                handle.abort();
            }
        }
    }
}

impl DomainRuntime {
    /// Db dsn.
    pub fn db_dsn(&self) -> Option<&str> {
        self.dbconn.db_dsn()
    }

    /// Abort workers.
    pub fn abort_workers(&self) {
        self.workers.abort_all();
    }

    /// Stamp a default tenant onto spawned engine contexts.
    pub fn with_tenant_id(mut self, tenant: Uuid) -> Self {
        self.tenant_id = Some(tenant);
        self
    }

    /// Test harness: Postgres pool with an injected stream bus.
    pub fn postgres_test(
        pgpool: Arc<PgPool>,
        db_dsn: String,
        logstore: DomainLogStore,
        stream_bus: Arc<dyn StreamBus>,
    ) -> Self {
        let msgbus = stream_bus.clone() as Arc<dyn MessageBus>;
        let process_manager = Arc::new(PostgresProcessManagerStore::new((*pgpool).clone()));
        Self {
            dbconn: DbConnection::Postgres(Arc::new(PgConnection { pgpool, db_dsn })),
            logstore,
            msgbus,
            stream_bus,
            workers: Arc::new(RuntimeWorkers::default()),
            invoker: CommandInvoker::new(),
            query_invoker: QueryInvoker::new(),
            process_manager,
            process_registry: ProcessManagerRegistry::new(),
            audit_log: AuditLogConfig::default(),
            tenant_id: Some(TEST_TENANT),
            deny_unknown_fields: false,
            media: MediaStorageConfig::default(),
            tenant_policies: TenantPolicyResolver::from_defaults(),
        }
    }

    /// Load from config: Postgres pool + audit logstore.
    pub async fn from_config(config: &RiverbaseConfig) -> RiverbaseResult<Self> {
        let db_dsn = config.db_url.clone();
        let dbpool = crate::datastore::postgres::establish_dbpool_with_options(
            &db_dsn,
            crate::config::DatabasePoolConfig::from_riverbase_config(config),
        )
        .await
        .map_err(|e| crate::errors::FLR_001.with_data(e.to_string()))?;
        let pgpool = Arc::new(dbpool);
        let bus_kind = config.bus.resolved_kind()?;
        info!(
            dbpool_max_size = config.dbpool_max_size,
            bus_kind = ?bus_kind,
            bus_url = %config.bus.resolved_url(),
            "Postgres connected (framework migrations applied)"
        );
        let logstore = PostgresDomainLogStore::new((*pgpool).clone())
            .into_bundle_with_config(&config.audit_log);
        let stream_bus = connect_stream_bus(config).await?;
        let msgbus = stream_bus.clone() as Arc<dyn MessageBus>;
        let workers = Arc::new(RuntimeWorkers::default());
        let process_registry = ProcessManagerRegistry::new();
        let process_manager: Arc<dyn ProcessManagerStore> =
            Arc::new(PostgresProcessManagerStore::new((*pgpool).clone()));
        workers.push(crate::command::spawn_outbox_publisher(
            logstore.outbox.clone(),
            msgbus.clone(),
        ));
        workers.push(spawn_process_manager_worker(
            process_manager.clone(),
            process_registry.clone(),
        ));
        Ok(Self {
            dbconn: DbConnection::Postgres(Arc::new(PgConnection {
                pgpool: pgpool.clone(),
                db_dsn,
            })),
            logstore,
            msgbus,
            stream_bus,
            workers,
            invoker: CommandInvoker::new(),
            query_invoker: QueryInvoker::new(),
            process_manager,
            process_registry,
            audit_log: config.audit_log.clone(),
            tenant_id: config
                .tenant_id
                .or_else(|| crate::base::tenant_id_from_config(&config.tenant)),
            deny_unknown_fields: config.deny_unknown_fields,
            media: config.media.clone(),
            tenant_policies: TenantPolicyResolver::new(
                config.tenant_access_policy.clone(),
                config.tenant_stamp_policy.clone(),
            ),
        })
    }
}
