//! Error catalogue for `riverbase_form`.

riverbase_core::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    FRM_001 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-001",
        message: "Form key must be exactly 8 characters (CCC-NNNN).",
    },
    FRM_002 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-002",
        message: "Form key prefix must be three letters.",
    },
    FRM_003 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-003",
        message: "Form key must contain a hyphen after the letter prefix.",
    },
    FRM_004 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-004",
        message: "Form key serial must be four digits.",
    },
    FRM_010 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-010",
        message: "Element spec failed JSON Schema validation.",
    },
    FRM_011 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-011",
        message: "Failed to deserialize element spec.",
    },
    FRM_012 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-012",
        message: "Failed to deserialize form spec.",
    },
    FRM_013 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-013",
        message: "Failed to deserialize document spec.",
    },
    FRM_014 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-014",
        message: "Form constraint cannot mix expr and JSON Schema keywords.",
    },
    FRM_015 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-015",
        message: "Form constraint must have expr or JSON Schema body.",
    },
    FRM_016 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-016",
        message: "Form spec failed JSON Schema validation.",
    },
    FRM_017 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-017",
        message: "Document spec failed JSON Schema validation.",
    },
    FRM_020 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-020",
        message: "Cannot read the form elements directory.",
    },
    FRM_030 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-030",
        message: "Form spec registry lock is poisoned.",
    },
    FRM_031 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-031",
        message: "Form spec key is already registered.",
    },
    FRM_040 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-040",
        message: "Failed to check out a Postgres connection for the form registry.",
    },
    FRM_041 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-041",
        message: "Failed to add form registry spec columns.",
    },
    FRM_042 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-042",
        message: "Failed to load element_registry rows.",
    },
    FRM_043 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-043",
        message: "Failed to load form_registry rows.",
    },
    FRM_044 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-044",
        message: "Failed to load template_registry rows.",
    },
    FRM_045 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-045",
        message: "Failed to look up an element_registry row.",
    },
    FRM_046 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-046",
        message: "Failed to upsert an element_registry row.",
    },
    FRM_047 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-047",
        message: "Failed to look up a form_registry row.",
    },
    FRM_048 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-048",
        message: "Failed to upsert a form_registry row.",
    },
    FRM_049 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-049",
        message: "Failed to look up a template_registry row.",
    },
    FRM_050 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-050",
        message: "No element HCL files found in elements directory.",
    },
    FRM_051 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-051",
        message: "Failed to create the form codegen Rust output directory.",
    },
    FRM_060 {
        status: 500,
        title: "Internal Server Error",
        code: "FRM-060",
        message: "Failed to apply riverbase_form database migrations.",
    },
    FRM_061 {
        status: 500,
        title: "Internal Server Error",
        code: "FRM-061",
        message: "Failed to connect to Postgres or run framework migrations.",
    },
    FRM_062 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-062",
        message: "Failed to register empty().",
    },
    FRM_063 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-063",
        message: "Failed to register coalesce().",
    },
    FRM_064 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-064",
        message: "Failed to register matches().",
    },
    FRM_065 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-065",
        message: "Failed to bind variable.",
    },
    FRM_066 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-066",
        message: "Constraint expression failed.",
    },
    FRM_067 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-067",
        message: "Constraint must be boolean.",
    },
    FRM_068 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-068",
        message: "Failed to create the form codegen migrations directory.",
    },
    FRM_069 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-069",
        message: "Failed to write generated form mod.rs.",
    },
    FRM_070 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-070",
        message: "Failed to write generated form schema.rs.",
    },
    FRM_071 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-071",
        message: "Failed to write generated form entities.rs.",
    },
    FRM_072 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-072",
        message: "Failed to create the form element migration directory.",
    },
    FRM_073 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-073",
        message: "Failed to write form element up.sql.",
    },
    FRM_074 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-074",
        message: "Failed to write form element down.sql.",
    },
    FRM_080 {
        status: 404,
        title: "Not Found",
        code: "FRM-080",
        message: "Docgen pipeline not found.",
    },
    FRM_081 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-081",
        message: "Failed to upsert a template_registry row.",
    },
    FRM_082 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-082",
        message: "Failed to register trim().",
    },
    FRM_083 {
        status: 422,
        title: "Unprocessable Content",
        code: "FRM-083",
        message: "Failed to register len().",
    },
    FRM_084 {
        status: 404,
        title: "Not Found",
        code: "FRM-084",
        message: "Form not found in registry.",
    },
}
