//! `AUT` error catalogue.

riverbase_core::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    AUT_001 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-001",
        message: "Authentication required.",
    },
    AUT_011 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-011",
        message: "OIDC discovery request failed.",
    },
    AUT_012 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-012",
        message: "OIDC discovery response parse failed.",
    },
    AUT_171 {
        status: 422,
        title: "Unprocessable Content",
        code: "AUT-171",
        message: "Auth routes require auth_provider = MockAuth or Keycloak.",
    },
    AUT_174 {
        status: 400,
        title: "Bad Request",
        code: "AUT-174",
        message: "X-Profile must be a valid UUID.",
    },
    AUT_180 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-180",
        message: "Failed to ensure riverbase_http_session schema.",
    },
    AUT_181 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-181",
        message: "Auth session store requires a Postgres domain runtime.",
    },
    AUT_182 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-182",
        message: "Authentication is required.",
    },
    AUT_183 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-183",
        message: "Authentication required to serve filtered OpenAPI document.",
    },
    AUT_184 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-184",
        message: "OIDC discovery HTTP status indicates failure.",
    },
    AUT_020 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-020",
        message: "JWKS request failed.",
    },
    AUT_021 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-021",
        message: "JWKS HTTP status indicates failure.",
    },
    AUT_022 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-022",
        message: "JWKS response parse failed.",
    },
    AUT_023 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-023",
        message: "JWKS RSA key is missing 'kid'.",
    },
    AUT_024 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-024",
        message: "JWKS RSA key is missing modulus 'n'.",
    },
    AUT_025 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-025",
        message: "JWKS RSA key is missing exponent 'e'.",
    },
    AUT_026 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-026",
        message: "JWKS RSA key material is invalid.",
    },
    AUT_027 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-027",
        message: "JWKS document contained no usable RSA keys.",
    },
    AUT_030 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-030",
        message: "OIDC issuer is required.",
    },
    AUT_031 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-031",
        message: "OIDC HTTP client build failed.",
    },
    AUT_032 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-032",
        message: "JWT header decode failed.",
    },
    AUT_033 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-033",
        message: "JWT header is missing kid.",
    },
    AUT_034 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-034",
        message: "Unsupported JWT algorithm.",
    },
    AUT_035 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-035",
        message: "JWT kid is not present in JWKS cache.",
    },
    AUT_036 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-036",
        message: "JWT validation failed.",
    },
    AUT_037 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-037",
        message: "JWT audience mismatch.",
    },
    AUT_038 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-038",
        message: "Authorization header must use Bearer scheme.",
    },
    AUT_039 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-039",
        message: "OIDC issuer mismatch.",
    },
    AUT_104 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-104",
        message: "Authenticated subject could not be resolved.",
    },
    AUT_106 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-106",
        message: "No organization resolved for authenticated user.",
    },
    AUT_130 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-130",
        message: "MockAuth HMAC secret is not configured (set client_secret or application_secret_key).",
    },
    AUT_146 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-146",
        message: "Access token has expired.",
    },
    AUT_149 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-149",
        message: "OAuth session missing PKCE verifier (session cookie not sent or expired).                   Use cookie_same_site = \"lax\" for cross-site Keycloak redirects.",
    },
    AUT_150 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-150",
        message: "Invalid access token: OAuth state mismatch",
    },
    AUT_151 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-151",
        message: "OAuth token exchange failed.",
    },
    AUT_152 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-152",
        message: "OAuth provider returned an error.",
    },
    AUT_153 {
        status: 400,
        title: "Bad Request",
        code: "AUT-153",
        message: "Missing authorization code",
    },
    AUT_154 {
        status: 400,
        title: "Bad Request",
        code: "AUT-154",
        message: "Missing ID token",
    },
    AUT_155 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-155",
        message: "Failed to establish the authenticated session.",
    },
    AUT_156 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-156",
        message: "Not logged in",
    },
    AUT_157 {
        status: 403,
        title: "Forbidden",
        code: "AUT-157",
        message: "Invalid CSRF token",
    },
    AUT_158 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-158",
        message: "User is not authenticated",
    },
    AUT_159 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-159",
        message: "Failed to persist the authenticated session.",
    },
    AUT_170 {
        status: 501,
        title: "Not Implemented",
        code: "AUT-170",
        message: "Profile switch is not supported.",
    },
    AUT_172 {
        status: 400,
        title: "Bad Request",
        code: "AUT-172",
        message: "Invalid mock authorization header.",
        hint: "Use `Authorization: MockAuth-<base64url(JSON claims)>` or omit the header.",
    },
    AUT_173 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-173",
        message: "Request context is missing a tenant identifier.",
        hint: "Auth profile setup must set tenant to a UUID.",
    },
    AUT_140 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-140",
        message: "JWT header decode failed.",
    },
    AUT_141 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-141",
        message: "JWT header is missing kid.",
    },
    AUT_142 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-142",
        message: "Unsupported JWT algorithm.",
    },
    AUT_143 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-143",
        message: "Public key not found for JWT kid.",
    },
    AUT_144 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-144",
        message: "Access token is malformed or invalid.",
    },
    AUT_145 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-145",
        message: "JWT audience mismatch.",
    },
    AUT_147 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-147",
        message: "JWT azp is not in the accepted list.",
    },
    AUT_160 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-160",
        message: "Session user is not authenticated.",
    },
    AUT_185 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-185",
        message: "Authentication request failed (AUT-130).",
    },
    AUT_186 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-186",
        message: "Authentication request failed (AUT-130).",
    },
    AUT_187 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-187",
        message: "Authentication request failed (AUT-130).",
    },
    AUT_188 {
        status: 400,
        title: "Bad Request",
        code: "AUT-188",
        message: "Authentication request failed (AUT-153).",
    },
    AUT_189 {
        status: 400,
        title: "Bad Request",
        code: "AUT-189",
        message: "Authentication request failed (AUT-153).",
    },
    AUT_190 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-190",
        message: "OAuth session missing PKCE verifier (session cookie not sent or expired).",
    },
    AUT_191 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-191",
        message: "PKCE verification failed.",
    },
    AUT_192 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-192",
        message: "Mock auth principal is not configured.",
    },
    AUT_193 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-193",
        message: "Authentication is required.",
    },
    AUT_194 {
        status: 500,
        title: "Internal Server Error",
        code: "AUT-194",
        message: "Mock auth principal is not configured.",
    },
    AUT_195 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-195",
        message: "Authentication is required.",
    },
    AUT_196 {
        status: 403,
        title: "Forbidden",
        code: "AUT-196",
        message: "This principal is not allowed on this API portal.",
    },
    AUT_197 {
        status: 400,
        title: "Bad Request",
        code: "AUT-197",
        message: "You are already signed in.",
        hint: "Go home to continue.",
    },
    AUT_198 {
        status: 401,
        title: "Unauthorized",
        code: "AUT-198",
        message: "Sign-in could not be completed.",
        hint: "Start sign-in again.",
    },
}
