//! `CFG` error catalogue.

riverbase_core::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    CFG_132 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-132",
        message: "omit_inaccessible_openapi requires authentication.",
        hint: "Disable omit_inaccessible_openapi, configure auth, or set RIVERBASE_INSECURE_ALLOW=omit-openapi-without-auth.",
    },
    CFG_140 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-140",
        message: "Casbin cannot run with authentication disabled.",
        hint: "Configure [riverbase.auth] or set RIVERBASE_INSECURE_ALLOW=auth-disabled-with-casbin.",
    },
    CFG_141 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-141",
        message: "Session signing key is missing or still the shipped default.",
        hint: "Set [riverbase.auth] application_secret_key or RIVERBASE_INSECURE_ALLOW=default-session-secret.",
    },
    CFG_142 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-142",
        message: "Keycloak auth requires a non-empty issuer.",
        hint: "Set [riverbase.auth] issuer or RIVERBASE_INSECURE_ALLOW=empty-keycloak-issuer.",
    },
    CFG_145 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-145",
        message: "api_zone is required.",
        hint: "Set [riverbase] api_zone or RIVERBASE_API_ZONE; each portal process must declare its deployment zone(s) at startup.",
    },
    CFG_148 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-148",
        message: "Keycloak auth requires a non-empty accepted_azp list.",
        hint: "Set [riverbase.auth] accepted_azp or RIVERBASE_AUTH_ACCEPTED_AZP.",
    },
    CFG_149 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-149",
        message: "Session cookies must be Secure and CSRF validation must be enabled.",
        hint: "Set cookie_https_only=true and validate_csrf_token=true, or RIVERBASE_INSECURE_ALLOW=insecure-cookies.",
    },
    CFG_150 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-150",
        message: "CORS cannot allow a wildcard origin together with credentials.",
        hint: "List explicit origins or disable credentials.",
    },
    CFG_152 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-152",
        message: "AuthenticatedApi posture requires authentication and Casbin.",
    },
    CFG_179 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-179",
        message: "Auth routes were requested but no auth provider is configured; set [riverbase.auth] auth_provider to \\\"MockAuth\\\" or \\\"Keycloak\\\" (or RIVERBASE_AUTH_DISABLED=1 to disable intentionally).",
    },
    CFG_181 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-181",
        message: "Link token secret is missing or still the shipped default.",
        hint: "Set RIVERBASE_LINK_TOKEN_SECRET or RIVERBASE_INSECURE_ALLOW=default-link-secret.",
    },
    CFG_182 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-182",
        message: "Link token salt is missing or still the shipped default.",
        hint: "Set RIVERBASE_LINK_TOKEN_SALT or RIVERBASE_INSECURE_ALLOW=default-link-salt.",
    },
    CFG_183 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-183",
        message: "Hook token secret is missing or still the shipped default.",
        hint: "Set RIVERBASE_HOOK_TOKEN_SECRET or RIVERBASE_INSECURE_ALLOW=default-hook-secret.",
    },
    CFG_184 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-184",
        message: "Hook token salt is missing or still the shipped default.",
        hint: "Set RIVERBASE_HOOK_TOKEN_SALT or RIVERBASE_INSECURE_ALLOW=default-hook-salt.",
    },
    CFG_204 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-204",
        message: "omit_inaccessible_openapi requires authentication; disable the flag or configure [riverbase.auth] (RIVERBASE_AUTH_DISABLED=1 is incompatible with this option).",
    },
    CFG_205 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-205",
        message: "CORS origins must be listed explicitly.",
        hint: "Call with_cors_origins with one or more origins.",
    },
    CFG_206 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-206",
        message: "Invalid CORS origin.",
    },
}
