//! `CFG` error catalogue.

crate::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    CFG_001 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-001",
        message: "Cannot read config file.",
    },
    CFG_002 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-002",
        message: "Configuration file contains invalid TOML.",
    },
    CFG_003 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-003",
        message: "Configuration section is invalid TOML.",
    },
    CFG_004 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-004",
        message: "Configuration value could not be parsed.",
    },
    CFG_010 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-010",
        message: "Failed to parse HCL.",
    },
    CFG_011 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-011",
        message: "Process HCL root must be an object.",
    },
    CFG_012 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-012",
        message: "`process` must be a labeled block map.",
    },
    CFG_020 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-020",
        message: "Failed to parse YAML.",
    },
    CFG_021 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-021",
        message: "Failed to parse YAML document.",
    },
    CFG_030 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-030",
        message: "Schema HCL root must be an object.",
    },
    CFG_031 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-031",
        message: "Schema HCL must define a top-level `schema` attribute or be a JSON Schema object.",
    },
    CFG_032 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-032",
        message: "Invalid JSON Schema.",
    },
    CFG_033 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-033",
        message: "Config failed JSON Schema validation.",
    },
    CFG_100 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-100",
        message: "Failed to build HTTP client.",
    },
    CFG_101 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-101",
        message: "ECR GetAuthorizationToken failed.",
    },
    CFG_110 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-110",
        message: "Failed to spawn `sops`. Is the sops binary installed and on PATH?",
    },
    CFG_111 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-111",
        message: "Failed to run sops to completion.",
    },
    CFG_120 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-120",
        message: "Invalid S3 URI.",
    },
    CFG_121 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-121",
        message: "Config URI scheme requires a disabled cargo feature.",
    },
    CFG_130 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-130",
        message: "Configuration payload is not valid UTF-8.",
    },
    CFG_131 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-131",
        message: "Configuration payload contains invalid YAML.",
    },
    CFG_143 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-143",
        message: "Hook token secret is not configured.",
        hint: "Set RIVERBASE_HOOK_TOKEN_SECRET.",
    },
    CFG_144 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-144",
        message: "Hook token salt is not configured.",
        hint: "Set RIVERBASE_HOOK_TOKEN_SALT.",
    },
    CFG_146 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-146",
        message: "Link token secret is not configured.",
        hint: "Set RIVERBASE_LINK_TOKEN_SECRET.",
    },
    CFG_147 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-147",
        message: "Link token salt is not configured.",
        hint: "Set RIVERBASE_LINK_TOKEN_SALT.",
    },
    CFG_151 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-151",
        message: "Bus scheme requires a cargo feature that is not enabled.",
    },
    CFG_160 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-160",
        message: "Unknown tenant_access_policy.",
    },
    CFG_161 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-161",
        message: "Unknown tenant_stamp_policy.",
    },
    CFG_162 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-162",
        message: "`domain-tenant` access requires a DomainTenantLookup provider.",
    },
    CFG_163 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-163",
        message: "Invalid HTTP(S) config URI.",
    },
    CFG_164 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-164",
        message: "S3 URI must be s3://bucket/key.",
    },
    CFG_165 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-165",
        message: "file:// URI has no path.",
    },
    CFG_166 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-166",
        message: "S3 URI must include both bucket and key.",
    },
    CFG_167 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-167",
        message: "Invalid git config URI (expected git+https://host/owner/repo//path[@ref]).",
    },
    CFG_168 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-168",
        message: "Config URI has no scheme.",
    },
    CFG_169 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-169",
        message: "Unsupported config URI scheme.",
    },
    CFG_170 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-170",
        message: "Invalid OCI URI (expected oci://registry/repository[:tag|@digest][//file]).",
    },
    CFG_171 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-171",
        message: "Unsupported config format.",
    },
    CFG_172 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-172",
        message: "Failed to stream ciphertext to sops.",
    },
    CFG_173 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-173",
        message: "SOPS decryption failed.",
    },
    CFG_174 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-174",
        message: "NATS bus requires the `nats-io` cargo feature.",
        hint: "Rebuild with riverbase_core feature `nats-io`, or set [riverbase.bus] kind = \"postgres\".",
    },
    CFG_175 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-175",
        message: "Redis bus requires the `redis` cargo feature.",
        hint: "Rebuild with riverbase_core feature `redis`, or set [riverbase.bus] kind = \"postgres\".",
    },
    CFG_176 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-176",
        message: "In-memory bus support was removed.",
        hint: "Use nats://host:4222, redis://host:6379, or postgresql://…",
    },
    CFG_177 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-177",
        message: "Bus URL is missing a scheme.",
        hint: "Use nats://host:4222, redis://host:6379, or postgresql://…",
    },
    CFG_178 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-178",
        message: "Unsupported bus URL scheme.",
        hint: "Use nats://, redis://, rediss://, postgresql://, or postgres://.",
    },
    CFG_180 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-180",
        message: "Failed to read configuration file.",
    },
    CFG_185 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-185",
        message: "YAML configuration requires the `yaml` cargo feature.",
        hint: "Rebuild with riverbase_core feature `yaml`, or use a TOML config.",
    },
    CFG_186 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-186",
        message: "Configuration payload contains invalid JSON.",
    },
    CFG_187 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-187",
        message: "Configuration value could not be parsed.",
    },
    CFG_188 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-188",
        message: "OCI artifact has no layers.",
    },
    CFG_189 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-189",
        message: "Failed to read local config file.",
    },
    CFG_190 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-190",
        message: "S3 GetObject failed.",
    },
    CFG_191 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-191",
        message: "HTTP config request failed.",
    },
    CFG_192 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-192",
        message: "Failed to read S3 object body.",
    },
    CFG_193 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-193",
        message: "Failed to read HTTP config body.",
    },
    CFG_194 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-194",
        message: "Git raw file request failed.",
    },
    CFG_195 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-195",
        message: "Failed to read git file body.",
    },
    CFG_196 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-196",
        message: "OCI manifest request failed.",
    },
    CFG_197 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-197",
        message: "Failed to parse OCI manifest.",
    },
    CFG_198 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-198",
        message: "OCI artifact has no layer matching the file selector.",
    },
    CFG_199 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-199",
        message: "OCI blob request failed.",
    },
    CFG_200 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-200",
        message: "Failed to read OCI blob body.",
    },
    CFG_201 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-201",
        message: "ECR returned no authorization token.",
    },
    CFG_202 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-202",
        message: "Google auth provider initialization failed.",
    },
    CFG_203 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-203",
        message: "Google access token fetch failed.",
    },
    CFG_207 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-207",
        message: "YAML single-document parse requires the `yaml` cargo feature.",
    },
    CFG_208 {
        status: 422,
        title: "Unprocessable Content",
        code: "CFG-208",
        message: "YAML document-stream parse requires the `yaml` cargo feature.",
    },
    CFG_209 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-209",
        message: "Git raw file request returned an error status.",
    },
    CFG_210 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-210",
        message: "HTTP config request returned an error status.",
    },
    CFG_211 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-211",
        message: "OCI manifest request returned an error status.",
    },
    CFG_212 {
        status: 500,
        title: "Internal Server Error",
        code: "CFG-212",
        message: "OCI blob request returned an error status.",
    },
}
