//! `CMD` error catalogue.

crate::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    CMD_002 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-002",
        message: "Command message payload validation failed.",
    },
    CMD_003 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-003",
        message: "Command does not allow this resource.",
    },
    CMD_004 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-004",
        message: "Object command requires an aggregate root.",
    },
    CMD_005 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-005",
        message: "Object commands require an aggregate root identifier.",
    },
    CMD_006 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-006",
        message: "Aggregate resource does not match command resource.",
    },
    CMD_007 {
        status: 404,
        title: "Not Found",
        code: "CMD-007",
        message: "Aggregate was not found.",
    },
    CMD_008 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-008",
        message: "Collection command must not include an aggregate root.",
    },
    CMD_010 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-010",
        message: "Failed to spawn the command engine actor.",
    },
    CMD_011 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-011",
        message: "Command payload could not be serialized.",
    },
    CMD_012 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-012",
        message: "Failed to dispatch command to the command engine actor.",
    },
    CMD_013 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-013",
        message: "Command engine did not return an execution result.",
    },
    CMD_014 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-014",
        message: "Command requires an explicit dispatch target.",
    },
    CMD_015 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-015",
        message: "Failed to request command registry items from the actor.",
    },
    CMD_016 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-016",
        message: "Command engine did not return the command registry list.",
    },
    CMD_017 {
        status: 404,
        title: "Not Found",
        code: "CMD-017",
        message: "Cannot update: row was not found.",
    },
    CMD_018 {
        status: 404,
        title: "Not Found",
        code: "CMD-018",
        message: "Command is not registered.",
    },
    CMD_021 {
        status: 409,
        title: "Conflict",
        code: "CMD-021",
        message: "A command with this Idempotency-Key is already in progress.",
    },
    CMD_022 {
        status: 409,
        title: "Conflict",
        code: "CMD-022",
        message: "Idempotency-Key was reused with a different request body.",
    },
    CMD_023 {
        status: 409,
        title: "Conflict",
        code: "CMD-023",
        message: "A prior command with this Idempotency-Key failed.",
    },
    CMD_024 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-024",
        message: "Failed to begin command transaction.",
    },
    CMD_025 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-025",
        message: "Failed to commit command transaction.",
    },
    CMD_027 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-027",
        message: "Command store claims transaction support but begin_command_transaction returned a non-transactional unit of work.",
    },
    CMD_028 {
        status: 403,
        title: "Forbidden",
        code: "CMD-028",
        message: "Action is not allowed on resource.",
    },
    CMD_029 {
        status: 501,
        title: "Not Implemented",
        code: "CMD-029",
        message: "Prepared command batch execution is not supported by this command engine.",
    },
    CMD_030 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-030",
        message: "Failed to dispatch prepared command batch to the command engine actor.",
    },
    CMD_031 {
        status: 500,
        title: "Internal Server Error",
        code: "CMD-031",
        message: "Command engine did not return a prepared batch execution result.",
    },
    CMD_032 {
        status: 422,
        title: "Unprocessable Content",
        code: "CMD-032",
        message: "Prepared command batch items must target the same command engine partition.",
    },
}
