//! `DAT` error catalogue.

crate::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    DAT_001 {
        status: 404,
        title: "Not Found",
        code: "DAT-001",
        message: "Diesel reported that the requested resource was not found.",
    },
    DAT_002 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-002",
        message: "Failed to translate a Diesel storage error.",
    },
    DAT_010 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-010",
        message: "Failed to acquire a database connection.",
    },
    DAT_011 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-011",
        message: "Database background task failed.",
    },
    DAT_012 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-012",
        message: "Failed to validate a database migration schema name.",
    },
    DAT_013 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-013",
        message: "Failed to create a database migration schema.",
    },
    DAT_014 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-014",
        message: "Failed to set the database migration search path.",
    },
    DAT_015 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-015",
        message: "Failed to run pending audit database migrations.",
    },
    DAT_016 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-016",
        message: "Failed to establish a connection for embedded database migrations.",
    },
    DAT_017 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-017",
        message: "Failed to run pending embedded database migrations.",
    },
    DAT_018 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-018",
        message: "Failed to establish the startup migration connection.",
    },
    DAT_019 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-019",
        message: "Failed to acquire the startup migration advisory lock.",
    },
    DAT_020 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-020",
        message: "Failed to release the startup migration advisory lock.",
    },
    DAT_021 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-021",
        message: "Failed to join the startup database migration task.",
    },
    DAT_022 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-022",
        message: "Failed to build the asynchronous database connection pool.",
    },
    DAT_023 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-023",
        message: "Failed to build the synchronous database connection pool.",
    },
    DAT_024 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-024",
        message: "Failed to acquire a connection to begin a command transaction.",
    },
    DAT_025 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-025",
        message: "Failed to begin a command transaction.",
    },
    DAT_026 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-026",
        message: "Failed to finish a command transaction.",
    },
    DAT_027 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-027",
        message: "Cannot use a command transaction after it has finished.",
    },
    DAT_028 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-028",
        message: "Failed to acquire a pooled connection for a datastore query.",
    },
    DAT_029 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-029",
        message: "Cannot acquire a Postgres command connection without a transaction.",
    },
    DAT_030 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-030",
        message: "Failed to acquire an asynchronous database connection.",
    },
    DAT_031 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-031",
        message: "Failed to acquire a synchronous database connection.",
    },
    DAT_032 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-032",
        message: "Failed to join a blocking Diesel database task.",
    },
    DAT_033 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-033",
        message: "Failed to parse a resource id as a UUID.",
    },
    DAT_034 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-034",
        message: "Cannot dispatch a datastore operation for an unregistered resource.",
    },
    DAT_035 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-035",
        message: "The requested Postgres datastore operation is not implemented.",
    },
    DAT_036 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-036",
        message: "Failed to deserialize a row returned by a Postgres list query.",
    },
    DAT_037 {
        status: 404,
        title: "Not Found",
        code: "DAT-037",
        message: "A Postgres item query returned no matching row.",
    },
    DAT_038 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-038",
        message: "Failed to deserialize a row fetched from Postgres.",
    },
    DAT_039 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-039",
        message: "Failed to deserialize a row fetched within a command transaction.",
    },
    DAT_040 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-040",
        message: "Failed to serialize a resource for a Postgres upsert.",
    },
    DAT_041 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-041",
        message: "Failed to serialize a resource for a Postgres compare-and-swap.",
    },
    DAT_042 {
        status: 404,
        title: "Not Found",
        code: "DAT-042",
        message: "The Postgres compare-and-swap target was not found.",
    },
    DAT_043 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-043",
        message: "Cannot merge a patch into a non-object datastore row.",
    },
    DAT_044 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-044",
        message: "Cannot merge a datastore patch that is not an object.",
    },
    DAT_045 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-045",
        message: "The requested resource is not allowed by the datastore registry.",
    },
    DAT_046 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-046",
        message: "Cannot create a datastore resource without a string id.",
    },
    DAT_047 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-047",
        message: "Failed to serialize a row while evaluating a default item query.",
    },
    DAT_048 {
        status: 404,
        title: "Not Found",
        code: "DAT-048",
        message: "The default item query found no row with the requested id.",
    },
    DAT_049 {
        status: 404,
        title: "Not Found",
        code: "DAT-049",
        message: "The find-one datastore query returned no rows.",
    },
    DAT_050 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-050",
        message: "The find-one datastore query returned multiple rows.",
    },
    DAT_051 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-051",
        message: "Failed to serialize a resource for a datastore insert.",
    },
    DAT_052 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-052",
        message: "Cannot insert a datastore resource without a string id.",
    },
    DAT_053 {
        status: 404,
        title: "Not Found",
        code: "DAT-053",
        message: "The default compare-and-swap target was not found.",
    },
    DAT_054 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-054",
        message: "Failed to serialize a patch for a datastore update.",
    },
    DAT_055 {
        status: 404,
        title: "Not Found",
        code: "DAT-055",
        message: "The datastore update target was not found.",
    },
    DAT_056 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-056",
        message: "Failed to deserialize the merged datastore update result.",
    },
    DAT_057 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-057",
        message: "Cannot lower an empty boolean filter to a Postgres predicate.",
    },
    DAT_058 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-058",
        message: "Cannot lower an empty membership filter to a Postgres predicate.",
    },
    DAT_059 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-059",
        message: "Cannot lower a between predicate whose operand is not an array.",
    },
    DAT_060 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-060",
        message: "Cannot lower a between predicate without exactly two bounds.",
    },
    DAT_061 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-061",
        message: "Cannot lower an empty overlap filter to a Postgres predicate.",
    },
    DAT_062 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-062",
        message: "Cannot bind an unsigned predicate beyond the Postgres BIGINT range.",
    },
    DAT_063 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-063",
        message: "Cannot bind a numeric predicate outside the supported range.",
    },
    DAT_064 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-064",
        message: "Cannot build a Postgres text-search predicate from an empty term.",
    },
    DAT_065 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-065",
        message: "Cannot build a Postgres text-search predicate without searchable tokens.",
    },
    DAT_066 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-066",
        message: "The requested Postgres filter operation is not supported.",
    },
    DAT_067 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-067",
        message: "Cannot render an empty AND filter as SQL.",
    },
    DAT_068 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-068",
        message: "Cannot render an empty OR filter as SQL.",
    },
    DAT_069 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-069",
        message: "Cannot render an empty IN filter as SQL.",
    },
    DAT_070 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-070",
        message: "Cannot render an empty NOT IN filter as SQL.",
    },
    DAT_071 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-071",
        message: "Cannot render a between filter without exactly two SQL bounds.",
    },
    DAT_072 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-072",
        message: "Cannot render an empty overlap filter as SQL.",
    },
    DAT_073 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-073",
        message: "Cannot render Postgres text-search SQL from an empty term.",
    },
    DAT_074 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-074",
        message: "Cannot render Postgres text-search SQL without searchable tokens.",
    },
    DAT_075 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-075",
        message: "The domain-entity query source is not supported.",
    },
    DAT_076 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-076",
        message: "The domain-entity order column is not supported.",
    },
    DAT_077 {
        status: 404,
        title: "Not Found",
        code: "DAT-077",
        message: "The domain-entity row to remove was not found.",
    },
    DAT_078 {
        status: 404,
        title: "Not Found",
        code: "DAT-078",
        message: "The domain-entity row to invalidate was not found.",
    },
    DAT_079 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-079",
        message: "The domain-entity filter column is not supported.",
    },
    DAT_080 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-080",
        message: "Cannot remove a row through a read-only Postgres entity.",
    },
    DAT_081 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-081",
        message: "Cannot invalidate a row through a read-only Postgres entity.",
    },
    DAT_082 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-082",
        message: "The read-only entity query source is not supported.",
    },
    DAT_083 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-083",
        message: "The read-only entity order column is not supported.",
    },
    DAT_084 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-084",
        message: "Cannot upsert a row through a read-only Postgres entity.",
    },
    DAT_085 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-085",
        message: "Failed to purge expired rows from an audit log channel.",
    },
    DAT_086 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-086",
        message: "Failed to warm up the database connection pool.",
    },
    DAT_090 {
        status: 409,
        title: "Conflict",
        code: "DAT-090",
        message: "A record with these values already exists.",
        hint: "Use a different value for the field that must be unique.",
    },
    DAT_091 {
        status: 409,
        title: "Conflict",
        code: "DAT-091",
        message: "A related record is missing or still in use.",
    },
    DAT_092 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-092",
        message: "A required field is missing.",
    },
    DAT_093 {
        status: 422,
        title: "Unprocessable Content",
        code: "DAT-093",
        message: "A value failed a database check constraint.",
    },
    DAT_094 {
        status: 409,
        title: "Conflict",
        code: "DAT-094",
        message: "The record overlaps an existing exclusion constraint.",
    },
    DAT_095 {
        status: 409,
        title: "Conflict",
        code: "DAT-095",
        message: "The database transaction conflicted with a concurrent update.",
        hint: "Retry the request.",
    },
    DAT_096 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-096",
        message: "The database rejected the write because the connection is read-only.",
    },
    DAT_097 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-097",
        message: "The database connection was closed before the operation finished.",
    },
    DAT_098 {
        status: 500,
        title: "Internal Server Error",
        code: "DAT-098",
        message: "Failed to send a command to the database.",
    },
}
