//! `DOM` error catalogue.

crate::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",
    DOM_002 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-002",
        message: "Command engine namespace does not match domain.",
    },
    DOM_003 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-003",
        message: "Duplicate command key in composite command engine.",
    },
    DOM_004 {
        status: 404,
        title: "Not Found",
        code: "DOM-004",
        message: "Command is not registered in this domain.",
    },
    DOM_005 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-005",
        message: "Query engine namespace does not match domain.",
    },
    DOM_006 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-006",
        message: "Duplicate query resource in composite query engine.",
    },
    DOM_007 {
        status: 404,
        title: "Not Found",
        code: "DOM-007",
        message: "Query resource is not registered in this domain.",
    },
    DOM_009 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-009",
        message: "Registered command is missing metadata.",
    },
    DOM_010 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-010",
        message: "Command registry key does not match command metadata.",
    },
    DOM_011 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-011",
        message: "Command metadata must declare at least one target resource.",
    },
    DOM_012 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-012",
        message: "Query registry and route metadata do not describe the same resources.",
    },
    DOM_013 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-013",
        message: "Duplicate domain contract.",
    },
    DOM_014 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-014",
        message: "Failed to serialize domain manifest.",
    },
    DOM_015 {
        status: 404,
        title: "Not Found",
        code: "DOM-015",
        message: "This domain does not expose command capability.",
    },
    DOM_016 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-016",
        message: "Aggregate state cannot be written outside an action.",
    },
    DOM_017 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-017",
        message: "Successful aggregate action produced no event.",
    },
    DOM_018 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-018",
        message: "Aggregate action session was not closed.",
    },
    DOM_020 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-020",
        message: "Migration dependency is not registered in this batch.",
    },
    DOM_021 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-021",
        message: "Duplicate migration name in ordered batch.",
    },
    DOM_022 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-022",
        message: "Migration dependency cycle detected.",
    },
    DOM_044 {
        status: 422,
        title: "Unprocessable Content",
        code: "DOM-044",
        message: "Unknown event key.",
        hint: "Register the event on the domain before recording it.",
    },
    DOM_045 {
        status: 403,
        title: "Forbidden",
        code: "DOM-045",
        message: "Command context is missing a tenant identifier.",
    },
    DOM_046 {
        status: 500,
        title: "Internal Server Error",
        code: "DOM-046",
        message: "All events must be consumed by the command handler.",
    },
    DOM_047 {
        status: 403,
        title: "Forbidden",
        code: "DOM-047",
        message: "Cannot resolve `_tenant` stamp from this policy.",
    },
    DOM_048 {
        status: 403,
        title: "Forbidden",
        code: "DOM-048",
        message: "No domain_tenant mapping for this namespace.",
    },
    DOM_049 {
        status: 403,
        title: "Forbidden",
        code: "DOM-049",
        message: "Command context has an empty tenant access list.",
    },
    DOM_050 {
        status: 403,
        title: "Forbidden",
        code: "DOM-050",
        message: "Only the owning tenant can transfer a row to another tenant.",
    },
}
